version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gothreatscope
    main: ./cmd/gothreatscope
    binary: gothreatscope
    env: [CGO_ENABLED=0]
    goos: [linux, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -trimpath
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats: [tar.gz]                # was: format: tar.gz (deprecated)
    format_overrides:                # was: format_overrides.format (deprecated)
      - goos: windows
        formats: [zip]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

source:
  enabled: true
  # default format is tar.gz; set explicitly if you want:
  # format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

checksum:
  name_template: checksums.txt

changelog:                       # top-level in v2 (not under release)
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'Merge pull request'

release:
  github:
    owner: anotherik
    name: GoThreatScope
  draft: false
  prerelease: false
