project_name: gothreatscope

builds:
  - id: gts
    main: ./cmd/gothreatscope
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: ["-trimpath"]
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - format: tar.gz
    builds: [gts]
    replacements: { darwin: macOS }
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums_{{ .Version }}.txt"
  algorithm: sha256

changelog:
  use: github
